### ISSUE TITLE
go.micro.client, service greeter: not found

### ISSUE THREAD

**Issue by zhivulinal** [micro/go-micro#1591] opened 2020-04-28 16:28 UTC
I see an error in the code from the example: https://github.com/micro/examples/tree/master/service
Run the service:
go run main.go
Run the client:
go run main.go --run_client
and get an error in the client terminal:
{"id":"go.micro.client","code":500,"detail":"service greeter: not found","status":"Internal Server Error"}

Everything is installed as here: https://micro.mu/docs/installation.html
MacOS Catalina

What am I doing wrong?

**Comment by x1nchen** [comment] 2020-05-12 17:35
micro use mdns as default registry.I reproduced your problem by delaying the query of mdns from client to 1s (default timeout). 

You  may check the service has already been registered on mdns server.

**Comment by tonymj76** [comment] 2020-05-16 12:33
@x1nchen please how did you did that am having the same error in my code.. if i use the cli command it query just find but my client code will result to that same problem

**Comment by zhivulinal** [comment] 2020-05-20 11:52
Hey.
This turned out to be an environmental error.
I just decided to restore the Mac OS system.
Now everything works

**Comment by asim** [comment] 2020-05-20 13:17
Closing since its environment related.

**Closed as completed by asim** 2020-05-20 13:17 UTC

**Comment by gr4yha7** [comment] 2020-05-27 08:30
I had a similar problem on my Ubuntu system when it wasn't connected to the internet.
Does mDNS require an internet connection?
I'm asking because everything worked fine when i turned my internet connection back on
