### ISSUE TITLE
Default selector round robin state not maintained

### ISSUE THREAD

**Issue by samcrutt-rb** [micro/go-micro#186] opened 2017-06-30 10:21 UTC
If I was to use the default selector with the round robin strategy then the state of the anonymous function is not maintained.

For example if I was to initialise the default selector and set the the round robin strategy on the default selector as follows:

`slct = selector.NewSelector(selector.Registry(registry), selector.SetStrategy(selector.RoundRobin))`

And then invoke Select on the default selector, I do not get the expected round robin behaviour. The algorithm for the round robin is fine and unit tests on that pass as expected. 
The issue lies around the use of the state within the anonymous function. The round robin strategy implementation is an anonymous function that increments the local variable i of the  enclosing function. This would work fine, but the Select method of the default selector creates a new Strategy function on every call, and therefore the state is reset.

**Comment by asim** [comment] 2017-06-30 11:42
This is by design. The default selector is not stateful, it's simplistic on purpose. It does no caching, it executes strategies and filters at the time of the request. If you want something more advanced then you must implement it. Example, there's a caching selector built in which watches the registry for changes and maintains a local cache for anything queried. There are a number of other selectors maintained here https://github.com/micro/go-plugins/tree/master/selector.

If you would like strategies to persist across selects then you must define something that understands how to manage this. An alternative approach is to use a client wrapper and let that manage state at the higher level so the selector is completely oblivious, in this case the strategy is passed in at time of selection which maintains counters for each service. You can find that in go-plugins https://github.com/micro/go-plugins/tree/master/wrapper/select/roundrobin

In the current implementation of the rpc client it executes select and receives a selector.Next function. This is executed to retrieve the next node, if the request fails and retries is higher than 1 it will call next again to get the next node. This is where the strategy currently comes into affect.

**Comment by asim** [comment] 2017-06-30 15:19
Closing due to the fact the implementation will not change and a solution has been given.

**Closed as completed by asim** 2017-06-30 15:19 UTC
