### ISSUE TITLE
consul registry broken: mismatch in type due to import being expected from "github.com/hashicorp/consul/vendor" 

### ISSUE THREAD

**Issue by desertjinn** [micro/go-micro#502] opened 2019-06-07 15:10 UTC
My Go version is 1.12.5.

I'm building my package binary using the **golang1.12.5-alpine3.9** Docker image as a package builder and I'm running the following commands in my _Dockerfile_ to install all the necessary dependencies - 

```
# install source dependencies
RUN go get -d -v ./...
RUN go install -v ./...
```

the  `go get` command works as expected but the `go install` command crashes with an exit code: 2 and the following message -

>
> \# github.com/micro/go-micro/registry/consul
> /go/src/github.com/micro/go-micro/registry/consul/watcher.go:48:33: cannot use cr.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
> /go/src/github.com/micro/go-micro/registry/consul/watcher.go:213:37: cannot use cw.r.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
> 

Just FYI, I was able to generate the Docker based package builder successfully up till 3 days ago.

**Comment by SteveZhangF** [comment] 2019-06-07 15:14
same here, got 

`../github.com/micro/go-micro/registry/consul/watcher.go:48:33: cannot use cr.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
../github.com/micro/go-micro/registry/consul/watcher.go:213:37: cannot use cw.r.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in a`

**Comment by asim** [comment] 2019-06-07 15:36
go get -u?

**Comment by desertjinn** [comment] 2019-06-07 15:55
Using `go get -u`
 instead of 
```
go get -d -v ./...
go install -v ./...

```

Response:
> directory "/go/src/<path/to/package directory>" is not using a known version control system

Also tried - `go get -u ...` with the same result 


@asim - just out of curiosity, **hashicorp/consul** appears to be in the process of enabling _go module_ support([see here](https://github.com/hashicorp/consul/issues/5713#issuecomment-486795072)). 
is that what's causing this?

**Comment by vtolstov** [comment] 2019-06-07 16:00
please, provide go env output

**Comment by desertjinn** [comment] 2019-06-07 16:07
@vtolstov -

Docker image: **golang:1.12.5-alpine3.9**

`go env` output:

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/root/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build607154663=/tmp/go-build -gno-record-gcc-switches"
>

**Comment by vtolstov** [comment] 2019-06-07 16:15
as i see you don't use go modules, so you have deps that conflict with each other.
try setting export GO111MODULE=on

**Comment by vtolstov** [comment] 2019-06-07 16:16
i don't understand why it work before..
also do you have all deps in vendor folder or download it in docker based package builder?

**Comment by SteveZhangF** [comment] 2019-06-07 16:20
I have the same issue with @desertjinn, using same docker image, it was work well yesterday, suddenly not working this morning.

@vtolstov tried `export GO111MODULE=on` still not working.

**Comment by vtolstov** [comment] 2019-06-07 16:23
if you try to add go mod vendor step before build and use go build -mod vendor  ?

**Comment by vtolstov** [comment] 2019-06-07 16:24
i think that hashicorp/consul dep changed in our module file..

**Comment by desertjinn** [comment] 2019-06-07 16:27
@vtolstov - I do not have a _vendor_ folder as I'm not using _go modules_ to manage dependencies in my package(cause from what I understand the _vendor_ folder is used by _go modules_)

And yeah, "hashicorp/consul" seem to be enabling go module support([see here](https://github.com/hashicorp/consul/issues/5713#issuecomment-486795072)) which might have caused this.

**Comment by vtolstov** [comment] 2019-06-07 16:29
if you don't have vendor dir, go with enabled modules download all deps when build package, if vendor exists - it gets it from here.
i think if you use go modules by default when get and build package it may work.
if you provide some easy reproducible steps i can try myself

**Comment by desertjinn** [comment] 2019-06-07 16:47
@vtolstov - tried with `export GO111MODULE=on` and it's not working for me either.
Also, I'm attempting to build packages from a private repository. So sharing my build steps might not be useful. 
Anyways, here's a sample of my _Dockerfile_
(the missing bits are for enabling access to my private repository)
```
# **************************************************
# start from golang 1.12.5 image based on ***
# alpine-3.9 **************************************
# **************************************************
FROM golang:1.12.5-alpine3.9

# **************************************************
# Add arguments to retrieve values from the ********
# CLI --build-args flag to the builder *************
# **************************************************
ARG ...
.....
.....

RUN apk add --no-cache ca-certificates git 

# **************************************************
# Configure container to use private repository ****
# instead of Go's default access pattern for *******
# the proper working of Go's dep package ***********
# (this ensures all the dependencies defined in ****
# the package files are available during ***********
# the build) ***************************************
# **************************************************
RUN ...
.....
.....
.....

# **************************************************
# Copy source files and build the Go binary **
# **************************************************
# create the necessary folders under Go's src
RUN mkdir -p /go/src/<private-repo>/<pacakge>
# switch to newly created folder for building the binary
WORKDIR /go/src/<private-repo>/<pacakge>
# copy source files
COPY . .
## install source dependencies
RUN go get -d -v ./...
RUN go install -v ./...

WORKDIR /go
```

Note that no build steps are available in the file as this is used only to generate the base Docker image that will be used further as a package builder.

**Comment by subzerobo** [comment] 2019-06-08 13:21
@asim 

my version is 1.12.5 same with 1.11.6 too 

It seems that this issue shows up when executing `go get -u github.com/micro/go-micro` even after I've cleaned up whole micro folder + hashicorp from github.com folder inside $GOPATH/src/github.com  

../../../micro/go-micro/registry/consul/watcher.go:48:33: cannot use cr.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
../../../micro/go-micro/registry/consul/watcher.go:213:37: cannot use cw.r.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger

**Comment by asim** [comment] 2019-06-08 14:23
We're not really responsible for consuls use of censoring and the mismatch in types. We're now using go modules to manage any dependencies and I can imagine hashicorp is doing this vendoring in related to their new sub package versioning.

Our builds show that this builds perfectly fine with go modules. If you otherwise have a fix please feel free to PR.

**Comment by subzerobo** [comment] 2019-06-08 15:26
@asim 
I know that, but consider someone is going to start with your project right now, for example, you said that in go.mod you will use github.com/hashicorp/consul/api v1.1.0, even in a clean $GOHOME/src/ when we run the go get -u github.com/micro/micro we get the error ?

https://travis-ci.org/micro/go-micro/jobs/541640654

**Comment by c-warren** [comment] 2019-06-08 18:16
I also saw this problem:
`$ make build
protoc -I. --go_out=plugins=micro:. \
	proto/course/course.proto
GOOS=linux GOARCH=amd64 go build`

github.com/micro/go-micro/registry/consul
../../../micro/go-micro/registry/consul/watcher.go:48:33: cannot use cr.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
../../../micro/go-micro/registry/consul/watcher.go:213:37: cannot use cw.r.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
Makefile:2: recipe for target 'build' failed
make: *** [build] Error 2

I ended up doing:
`$ go clean -modcache`  
`$ export GO111MODULE=on`      
`$ go get -u`  
And now I have my builds working.

**Comment by asim** [comment] 2019-06-08 18:58
Hashicorp have included a vendor directory as of yesterday which causes this break. Using go modules seems to be the only solution for now. We need to file an issue with them or find a way to resolve this vendoring issue.

**Comment by desertjinn** [comment] 2019-06-08 22:40
Switched to using go modules for managing packages and it works as expected now

**Comment by asim** [comment] 2019-06-09 07:57
Closing the issue

**Closed as completed by asim** 2019-06-09 07:57 UTC
