### ISSUE TITLE
data race in server

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#412] opened 2019-02-02 08:00 UTC
```
==================
WARNING: DATA RACE
Write at 0x00c00032b410 by goroutine 249:
  runtime.mapassign_faststr()
      /var/home/vtolstov/sdk/go1.12beta2/src/runtime/map_faststr.go:202 +0x0
  github.com/micro/go-micro/server.(*rpcServer).Register()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:285 +0x342
  github.com/micro/go-micro/server.(*rpcServer).Start.func2()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:513 +0x1c9

Previous read at 0x00c00032b410 by goroutine 158:
  runtime.mapaccess1_faststr()
      /var/home/vtolstov/sdk/go1.12beta2/src/runtime/map_faststr.go:12 +0x0
  github.com/micro/go-micro/client.(*rpcClient).call()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/client/rpc_codec.go:133 +0x5ef
  github.com/micro/go-micro/client.(*rpcClient).call-fm()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/client/rpc_client.go:61 +0x11a
  github.com/micro/go-micro/client.(*rpcClient).Call.func1()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/client/rpc_client.go:380 +0x5d4
  github.com/micro/go-micro/client.(*rpcClient).Call.func2()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/client/rpc_client.go:390 +0x3d
Goroutine 249 (running) created at:
  github.com/micro/go-micro/server.(*rpcServer).Start()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:496 +0x848
  github.com/micro/go-micro.(*service).Start()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:80 +0x104
  github.com/micro/go-micro.(*service).Run()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:116 +0x50
  unistack.org/centralv2/server.runService()
      /home/vtolstov/devel/projects/centralv2/server/server.go:110 +0x5c

Goroutine 158 (finished) created at:
  github.com/micro/go-micro/client.(*rpcClient).Call()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/client/rpc_client.go:389 +0x728
      /home/vtolstov/devel/projects/centralv2/service/scheduler/schedulerpb/scheduler.micro.go:91 +0x1b4
  unistack.org/centralv2/service/instance.(*instanceServer).Create()
      /home/vtolstov/devel/projects/centralv2/service/instance/handlers.go:149 +0x1ca6
  unistack.org/centralv2/service/instance/instancepb.(*instanceServiceHandler).Create()
      /home/vtolstov/devel/projects/centralv2/service/instance/instancepb/instance.micro.go:163 +0x7c
  unistack.org/centralv2/service/instance/instancepb.(*InstanceService·2).Create()
      <autogenerated>:1 +0x91
  runtime.call64()
      /var/home/vtolstov/sdk/go1.12beta2/src/runtime/asm_amd64.s:520 +0x3a
  reflect.Value.Call()
      /var/home/vtolstov/sdk/go1.12beta2/src/reflect/value.go:308 +0xc0
  github.com/micro/go-micro/server.(*service).call.func1()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_router.go:195 +0x29d
  github.com/micro/go-micro/server.(*service).call()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_router.go:206 +0xc49
  github.com/micro/go-micro/server.(*router).ServeRequest()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_router.go:445 +0x291
  github.com/micro/go-micro/server.(*rpcServer).ServeConn.func2()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:151 +0xcd
  github.com/unistack-org/go-plugins/wrapper/monitoring/prometheus.NewHandlerWrapper.func1.1()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/unistack-org/go-plugins/wrapper/monitoring/prometheus/prometheus.go:67 +0x238
  github.com/micro/go-micro/server.(*rpcServer).ServeConn()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:159 +0xb03
  github.com/micro/go-micro/server.(*rpcServer).ServeConn-fm()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:49 +0x55
  github.com/micro/go-micro/transport.(*httpTransportListener).Accept.func1()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/transport/http_transport.go:398 +0x378
  net/http.HandlerFunc.ServeHTTP()
      /var/home/vtolstov/sdk/go1.12beta2/src/net/http/server.go:1995 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /var/home/vtolstov/sdk/go1.12beta2/src/net/http/server.go:2375 +0x28a
  golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP()
      /home/vtolstov/devel/projects/centralv2/vendor/golang.org/x/net/http2/h2c/h2c.go:98 +0x1d8
  golang.org/x/net/http2/h2c.(*h2cHandler).ServeHTTP()
      <autogenerated>:1 +0x9d
  net/http.serverHandler.ServeHTTP()
      /var/home/vtolstov/sdk/go1.12beta2/src/net/http/server.go:2774 +0xc4
  net/http.(*conn).serve()
      /var/home/vtolstov/sdk/go1.12beta2/src/net/http/server.go:1878 +0x807
==================

**Comment by vtolstov** [comment] 2019-02-02 08:02
IMHO this data race bring often after upgrade go-micro to master in last 3 days and enable RegisterInterval

**Comment by vtolstov** [comment] 2019-02-02 08:09
i'm try to add lock on map, but as i see this is not helps
```
diff --git a/server/rpc_server.go b/server/rpc_server.go
index de3b8fd37d27..d9591a5367ed 100644
--- a/server/rpc_server.go
+++ b/server/rpc_server.go
@@ -282,11 +282,13 @@ func (s *rpcServer) Register() error {
                Metadata: config.Metadata,
        }

+       s.Lock()
        node.Metadata["transport"] = config.Transport.String()
        node.Metadata["broker"] = config.Broker.String()
        node.Metadata["server"] = s.String()
        node.Metadata["registry"] = config.Registry.String()
        node.Metadata["protocol"] = "mucp"
+       s.Unlock()

        s.RLock()
        // Maps are ordered randomly, sort the keys for consistency
```

**Comment by asim** [comment] 2019-02-02 08:45
Because you are running this in a single process it's accessing the same data in the client and the server. This data should actually be transferred over a connection. This goes back to the fact that it's not built to be run in a single process.

**Comment by vtolstov** [comment] 2019-02-02 10:41
may be i miss something, but why client and server shares the same data?i think that client need to copy all passed pointer data, so after client is created you can't modify it runtime data... also for server too.

**Comment by vtolstov** [comment] 2019-02-02 10:46
or you mean server from one service accepts data from client of another service?

**Comment by asim** [comment] 2019-02-02 10:47
Here's the flow you're seeing.

1. Server registers itself with the registry
2. Client looks up the registry to call that service
3. Server re-registers that data while client is using it

Because this is all in a single process the same data is being accessed and modified. If this was multi-process that would not happen. We should likely make copies of the data somewhere but the problem is linked to single process development.

**Comment by vtolstov** [comment] 2019-02-03 13:09
thanks, can you tag this issue with monolith ?

**Comment by vtolstov** [comment] 2019-02-04 09:42
i'm rewrite some stuff, now transport created in each service independent. so in cmd i'm only parse options and create option slice.
so transport releted races don't be issue now, only if NewTransport does not copy passed options.
If i create registry in each service , does it solve issue that you write above?

**Comment by vtolstov** [comment] 2019-02-04 10:38
no, this is not fixes, i'm already try this in own branch. now i'm try to init registry, broker and transport in each service independent and check result.

**Comment by vtolstov** [comment] 2019-02-04 14:44
Now i'm only pass preconfigured Broker and Registry. Transport, Selector, Server, Client created on each service independent. Now i don't see any races.

**Comment by asim** [comment] 2019-02-04 14:51
Should we mark this as resolved then?

**Closed as completed** 2019-02-04 15:45 UTC

**Comment by vtolstov** [comment] 2019-02-04 16:40
Yes,thanks.
