### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by cooldog21** [micro/go-micro#530] opened 2019-06-20 04:38 UTC
# github.com/micro/go-micro/registry/consul
src/github.com/micro/go-micro/registry/consul/watcher.go:47:33: cannot use cr.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
src/github.com/micro/go-micro/registry/consul/watcher.go:212:37: cannot use cw.r.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger

**Comment by asim** [comment] 2019-06-20 06:05
Duplicate of https://github.com/micro/go-micro/issues/527

**Closed as completed by asim** 2019-06-20 06:05 UTC

**Comment by cooldog21** [comment] 2019-06-20 07:02
thx
